[package]
name = "runner-tui"
description = "A terminal based file browser"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/alexm-dev/runner"
readme = "README.md"
authors = ["alexm-dev"]
categories = ["filesystem", "command-line-utilities", "command-line-interface"]
keywords = ["file-browser", "file-manager", "tui", "cli", "search"]

[[bin]]
name = "rn"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
ratatui = "0.29.0"
crossterm = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
